require("mock_hs")
local windowManager = require("init")

describe("window_manager_full_screen", function()
	it("should full full screen view", function()
		local frame = windowManager:mmaximize()
		assert.is.equal(frame.x, 0)
		assert.is.equal(frame.y, 0)
		assert.is.equal(frame.w, 300)
		assert.is.equal(frame.h, 351)
	end)

	it("should full full screen when maximize with gap 0", function()
		windowManager:setGaps(0, 0)
		local frame = windowManager:maximize()
		assert.is.equal(frame.x, 0)
		assert.is.equal(frame.y, 0)
		assert.is.equal(frame.w, 300)
		assert.is.equal(frame.h, 351)
	end)

	it("should full screen with gap", function()
		windowManager:setGaps(1, 0)
		local frame = windowManager:maximize()
		assert.is.equal(frame.x, 1)
		assert.is.equal(frame.y, 1)
		assert.is.equal(frame.w, 298)
		assert.is.equal(frame.h, 349)
	end)

	it("should full screen with gap", function()
		windowManager:setGaps(2, 10)
		local frame = windowManager:maximize()
		assert.is.equal(frame.x, 2)
		assert.is.equal(frame.y, 2)
		assert.is.equal(frame.w, 296)
		assert.is.equal(frame.h, 347)
	end)
end)

describe("window_manager_half", function()
	it("should left half no gap", function()
		windowManager:setGaps(0, 0)
		local frame = windowManager:leftHalf()
		assert.is.equal(frame.x, 0)
		assert.is.equal(frame.y, 0)
		assert.is.equal(frame.w, 150)
		assert.is.equal(frame.h, 351)
	end)
	it("should left half with outter gap", function()
		windowManager:setGaps(1, 0)
		local frame = windowManager:leftHalf()
		assert.is.equal(frame.x, 1)
		assert.is.equal(frame.y, 1)
		assert.is.equal(frame.w, 149)
		assert.is.equal(frame.h, 349)
	end)
	it("should left half with outter gap and inner gap", function()
		windowManager:setGaps(8, 11)
		local frame = windowManager:leftHalf()
		assert.is.equal(frame.x, 8)
		assert.is.equal(frame.y, 8)
		assert.is.equal(frame.w, 137)
		assert.is.equal(frame.h, 335)
	end)
end)
